name: percy tests

on:
  push:
    branches:
      - '**'

jobs:
  percy_tests:
      if: ${{ !contains(github.event.head_commit.message, '#skippercy') }}
      name: percy visual tests
      runs-on: ubuntu-latest
      needs: get_vercel_url
      steps:
        - name: Checkout files
          uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '14'
        - name: Get target url
        - name: Run cypress <> percy tests
          uses: cypress-io/github-action@v2
          env:
              PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
              BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
              BROWSERSTACK_ACCESS_KEY: ${{ secrets. BROWSERSTACK_ACCESS_KEY }}
          with:
              install: true
              working-directory: cypress-tests
              command: yarn percy:run --build-name "percy-demo/${{github.run_number}}" --local true --local-identifier "percy-demo-${{github.run_id}}-${{github.run_attempt}}"
