name: percy tests

on:
  push:
    branches:
      - '**'

jobs:
  percy_tests:
      name: percy visual tests
      runs-on: ubuntu-latest
      steps:
        - name: Checkout files
          uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '16'
        - name: Run cypress <> percy tests
          uses: cypress-io/github-action@v2
          env:
              PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
              BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
              BROWSERSTACK_ACCESS_KEY: ${{ secrets. BROWSERSTACK_ACCESS_KEY }}
          with:
              install: true
              command: yarn run:percy --build-name "percy-demo/${{github.run_number}}" --local-identifier "percy-demo-${{github.run_id}}-${{github.run_attempt}}"
